version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop-minitest
    versions:
    - 0.10.3
    - 0.11.0
    - 0.11.1
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.8.1
    - 1.9.1
  - dependency-name: codecov
    versions:
    - 0.4.0
    - 0.4.2
    - 0.5.1
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.2
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: faraday
    versions:
    - 1.3.0
  - dependency-name: minitest
    versions:
    - 5.14.3
